### ISSUE TITLE
Explore OpenLabeling

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/vision-tech#3]
Explore the above annotation tool and share your thoughts

https://github.com/Cartucho/OpenLabeling

**Comment by johnkaramchand** [comment]
Installation is straightforward, install dependencies and run the program. 

A pretty intuitive UI for labeling. Uses the keyboard to shift classes and images while the mouse is used to draw bounding boxes.

![pic1]
![keyboard_usage](https://github.com/cia-labs/vision-tech/assets/7531229/29f64a6c-a2dd-44af-b4d3-adccf902d2cf)
(https://github.com/cia-labs/vision-tech/assets/7531229/d22924bb-4451-44bc-a288-ca20f1598363)

All files in a particular folder are considered and for every image that is labelled, a corresponding file  for different annotation formats is generated. 

![pic2](https://github.com/cia-labs/vision-tech/assets/7531229/22e8fc8d-061d-4cff-95ce-2771d443d5c2)
