### ISSUE TITLE
Feral's previous labeling strategy

### ISSUE THREAD

**Issue by Tejas-ChandraShekarRaju** [cia-labs/vision-tech#5]
**What kind of labeling was done previously on the model feral used to train?**

1. Bounding box annotation - which is basically drawing a rectangle where the object is present, in our case where the elephant is present. 
2. Semantic segmentation Labeling - drawing exact boundaries on objects that you want to identify. In our case ear, trunk etc. - Tried in labelMg
3. Instance segmentation labeling - 
4. Keypoint labeling - 
5. Attribute labeling - labeling age, gender etc. I don’t think it’s that useful for us.

**Comment by johnkaramchand** [comment]
BLTN;
The process was that a human (expert) would look at a picture, label segments "in their mind" and note down the segment's classes in an excel sheet.
